schedules:
  commit:
    # Run short and medium suites on commit, on DSE 6.8 only.
    schedule: per_commit
    matrix:
      exclude:
        - java: ['openjdk11']
        - cassandra: ['dse-6.7', 'dse-6.0', 'dse-5.1', 'dse-5.0', 'dse-4.8', 'dse-4.7', '3.11', '3.0', '2.2', '2.1']
    env_vars: |
      TEST_GROUPS="medium"
  nightly:
    # Run full suite nightly on change for all primary branches if they have changes.
    schedule: nightly
    branches:
      # regex matches primary branch format (1.1, 1.x, 1.1.x, etc).
      include: ["/\\d+(\\.[\\dx]+)+/"]
    env_vars: |
      TEST_GROUPS="medium,long"
  adhoc:
    # Run full suite on demand.
    schedule: adhoc
    matrix:
      exclude:
        - java: ['openjdk11']
    env_vars: |
      TEST_GROUPS="medium,long"
java:
  - openjdk8
  - openjdk11
os:
  - ubuntu/bionic64/java-driver
cassandra:
  - 2.1
  - 2.2
  - 3.0
  - 3.11
  - dse-4.7
  - dse-4.8
  - dse-5.0
  - dse-5.1
  - dse-6.0
  - dse-6.7
  - dse-6.8
build:
  - type: maven
    version: 3.2.5
    goals: verify -P$TEST_GROUPS --fail-never -B
    properties: |
      dsbulk.ccm.CCM_VERSION=$CCM_VERSION
      dsbulk.ccm.CCM_IS_DSE=$CCM_IS_DSE
      dsbulk.ccm.JAVA_HOME=$CCM_JAVA_HOME
      dsbulk.ccm.PATH=$CCM_JAVA_HOME/bin
      dsbulk.cloud.PROXY_PATH=$HOME/proxy
      failIfNoTests=false
      maven.test.failure.ignore=true
      maven.javadoc.skip=true
  - xunit:
      - "**/target/surefire-reports/TEST-*.xml"
      - "**/target/failsafe-reports/TEST-*.xml"
  - jacoco:
    exec_pattern: "**/target/**.exec"
    exclusion_pattern: "**/generated/**"
